---
- name: Create new nginx web root folder
  file: path=/var/html state=directory mode=0777

- name: Configure nginx web root folder in Ubuntu
  when: ansible_os_family == "Debian"
  copy: src=default dest=/etc/nginx/sites-available/default
  notify:
     - Restart nginx web server

- name: Configure nginx web root folder in CentOS 
  when: ansible_os_family == "RedHat"
  copy: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify:
     - Restart nginx web server

...
