- name: Demonstrates use of docker_container module and sequence loop
  hosts: localhost
  tasks:
#    - name: Install pip tool
#      apt: name=python-pip state=latest update_cache=yes

#    - name: Install docker-py python module using pip
#      shell: pip install docker-py
     
#    - name: Remove all existing containers
#      shell: docker rm -f $(docker ps -aq)
#      ignore_errors: True

    - name: Create an Ubuntu container
      docker_container:
          name: "ubuntu{{item}}"
          hostname: "ubuntu{{item}}"
          image: "tektutor/ansible-ubuntu"
          state: started 
          ports:
            - "200{{item}}:22"
            - "800{{item}}:80"
      with_sequence: start=1 end=3

    - name: Create an CentOS container
      docker_container:
          name: "centos{{item}}"
          hostname: "centos{{item}}"
          image: "tektutor/ansible-centos"
          state: started 
          ports:
            - "300{{item}}:22"
            - "900{{item}}:80"
      with_sequence: start=1 end=3

- name: Ping all containers
  hosts: all
  tasks:
    - name: Ping the newly created container
      ping: 
