- name: Retrieve IP Address of Docker container
  hosts: all
  tasks:
    - shell: ifconfig $(route | grep default | awk '{print $(NF)}') | grep 'inet' | awk '{ print $2}'
      register: ipv4_address

    - debug: var=ipv4_address.stdout

